config/routes.rb
Curso::Application.routes.draw do
  resources :departamentos
  resources :funcionarios

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  attr_accessible :nome

  has_many :funcionarios
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  attr_accessible :admissao, :departamento_id, :nome

  belongs_to :departamento
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departamentos }
    end
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @departamento = Departamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/new
  # GET /departamentos/new.json
  def new
    @departamento = Departamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/1/edit
  def edit
    @departamento = Departamento.find(params[:id])
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(params[:departamento])

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render json: @departamento, status: :created, location: @departamento }
      else
        format.html { render action: "new" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departamentos/1
  # PUT /departamentos/1.json
  def update
    @departamento = Departamento.find(params[:id])

    respond_to do |format|
      if @departamento.update_attributes(params[:departamento])
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento = Departamento.find(params[:id])
    @departamento.destroy

    respond_to do |format|
      format.html { redirect_to departamentos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/funcionarios_controller.rb
#encoding: utf-8

class FuncionariosController < ApplicationController

	def index
		@funcionarios = Funcionario.all
	end

	def show
		@funcionario = Funcionario.find(params[:id])
	end

	def edit
		@funcionario = Funcionario.find(params[:id])
		@departamentos = Departamento.all
	end

	def update
	    @funcionario = Funcionario.find(params[:id])

	    date = params[:funcionario][:admissao]
	    @funcionario.admissao = text_to_date(date)

		if @funcionario.update_attributes(params[:funcionario])
			redirect_to @funcionario, notice: 'Funcionário atualizado com sucesso.'
		else
			render action: "edit"
	    end
	end

	def new
		@funcionario = Funcionario.new
		@departamentos = Departamento.all
	end

	def destroy
	
	    @funcionario = Funcionario.find(params[:id])
	    @funcionario.destroy

	    redirect_to funcionarios_url
	      
	end

	def create
    	@funcionario = Funcionario.new(params[:funcionario])
	 
		if @funcionario.save
			redirect_to @funcionario, notice: 'Funcionário criado com sucesso.'
		else
			render action: "new"
		end
	
	end

	private
		
		def text_to_date(text)
			parts = text.split("/")
			Date.new parts[2].to_i, parts[1].to_i, parts[0].to_i
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/departamentos/_form.html.erb
<%= form_for(@departamento) do |f| %>
  <% if @departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% @departamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<h1>Listing departamentos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departamentos.each do |departamento| %>
  <tr>
    <td><%= departamento.nome %></td>
    <td><%= link_to 'Show', departamento %></td>
    <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
    <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New departamento</h1>

<%= render 'form' %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @departamento.nome %>
</p>


<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario, :html => {:class => "form-horizontal"}) do |f| %>
	<div class="control-group">
		<%= f.label :nome, "Nome: ", :class => "control-label" %>
		<div class="controls">
			<%= f.text_field :nome %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :departamento_id, "Departamento: ", :class => "control-label" %>
		<div class="controls">
			<%= f.select :departamento_id, options_from_collection_for_select(@departamentos, 'id', 'nome', @funcionario.departamento_id) %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :admissao, "Admissao :", :class => "control-label" %>
		<div class="controls">
			<%= f.text_field :admissao, :class => "date", :value => "#{@funcionario.admissao.strftime("%d/%m/%Y") if @funcionario.admissao}" %>
		</div>
	</div>
	<div class="form-actions">
		<%= f.submit :class => "btn btn-primary", :value => "Gravar" %>
		<%= link_to "Voltar", funcionarios_path, :class => "btn" %>
	</div>
<% end %>

app/views/funcionarios/edit.html.erb
<h3>Editar Funcionario</h3>

<%= render 'form' %>

app/views/funcionarios/index.html.erb
<h5>Funcionários</h5>
<table class="table table-striped">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Departamento</th>
				<th>Admissão</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<% @funcionarios.each do |funcionario| %>
				<tr>
					<td><%= funcionario.nome %></td>
					<td><%= funcionario.departamento.nome if funcionario.departamento %></td>
					<td><%= funcionario.admissao.strftime("%d/%m/%Y") if funcionario.admissao %></td>
					<td><%= link_to 'Show', funcionario, :class=>'btn' %></td>
				    <td><%= link_to 'Edit', edit_funcionario_path(funcionario), :class=>'btn' %></td>
				    <td><%= link_to 'Destroy', funcionario, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn' %></td>
				</tr>
			<% end %>	
		</tbody>
</table>

<%= link_to 'Incluir', new_funcionario_path, :class => "btn btn-primary" %>

<br><br>

app/views/funcionarios/show.html.erb
	<h2>Funcionário</h2>
	<p>
		<strong>Nome</strong>
		<%= @funcionario.nome if @funcionario.nome%>
	</p>
	<p>
		<strong>Departamento</strong>
		<%= @funcionario.departamento.nome if @funcionario.departamento %>
	</p>
	<p>
		<strong>Admissão</strong>
		<%= @funcionario.admissao.strftime("%d/%m/%Y") if @funcionario.admissao %>
	</p>
	<a href="/funcionarios" class="btn">Voltar</a>
    <%= link_to 'Editar', edit_funcionario_path(@funcionario), :class=>'btn' %>
    <%= link_to 'Detonar', @funcionario, method: :delete, data: { confirm: 'Detonar agora mano?' }, :class=>'btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Curso</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="container header">
			<h1>Curso Rails SAMA</h1>
		</div>
	</header>
	<nav>
		<div class="container">
			<ul id="menu">
				<li class="first">
					<a href="/departamentos" <% current_page? puts "class='active'" %>>Departamentos</a>
				</li>
				<li>
					<a href="/funcionarios">Funcionários</a>
				</li>
			</ul>
			<div class="clear"></div>
		</div>
	</nav>
	<div class="container home ">
		<%= yield %>
	</div>

	<!--<footer>
		<div class="container">
			Curso ministrado por <a href="http://github.com/pbalduino" target="_blank">Plínio Balduíno</a>
		</div>
	</footer>-->
</body>
</html>